const maps = [
    [
        `
        ___________________ggggggggggggggggggg
        ___________________ggggggggggggggggggg
        ______________________________________
        ______________________________________
        ______________________________________
        ___________________ggggggggggggggggggg
        ______________________________________
        ______________________________________
        ___________________ggggggggggggggggggg
        _______________q______________________
        ______________________________________
        ___________________ggggggggggggggggggg
        ___s__________________________________
        gggggggggggggggggggggggggggggggggggggg
        gggggggggggggggggggggggggggggggggggggg
        `
    ]
];